# Generated by Django 3.2.3 on 2021-05-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('sort_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'focus_actor',
                'managed': False,
            },
        ),
    ]
